// source.config.ts
/** biome-ignore-all lint/suspicious/noVar: <generated by fumadocs> */
import {
  defineCollections,
  defineConfig,
  frontmatterSchema,
} from "fumadocs-mdx/config";
import { z } from "zod";

var blog = defineCollections({
  type: "doc",
  dir: "content/blog",
  schema: frontmatterSchema.extend({
    date: z.string().date(),
    author: z.string().default("Martin Vila"),
  }),
});
var source_config_default = defineConfig();
export { blog, source_config_default as default };
